### ISSUE TITLE
[BUILD]:'LIBHTTPSERVER_DIR' variable not taken into account in the ".mk" files

### ISSUE THREAD

**Issue by rahmanih** [ouistiti-project/ouistiti#32]
Hi,
the **LIBHTTPSERVER_DIR** Build variable is supposed pointing to the sources of the _libhttpserver_ that could be outside the "ouistiti" root dir. This variable should be used in the ".mk" files to add the "libhttpserver" in the Include paths but it is not which leads to a build error:

Error type:
`
mod_document.c:39:35: fatal error: httpserver/httpserver.h: No such file or directory
`
 Fix: use the **LIBHTTPSERVER_DIR** in  the .mk files
`
-mod_document_CFLAGS+=-DSTATIC_FILE -I../libhttpserver/include
`
`
+mod_document_CFLAGS+=-DSTATIC_FILE -I$(LIBHTTPSERVER_DIR)/include
`
regards
Haithem.

**Comment by mchalain** [comment]
Thank you for the information I will check quickly.

Currently you can build and install libhttpserver first. And after build
ouistiti.
Another way is to make a link from libhttpserver into ouistiti

Regards,
Marc.

**Comment by mchalain** [comment]
Hello,
I made few corrections on the build of Ouistiti. Effectively, the path to
libhttpserver was useless, and it wasn able to give another path.
The correction should allow to set the path to the sources directory of
libhttpserver or the path to the installation or nothing if the
installation is standard.
I had some other correction about the security of each process.

Thank you for your remark.
regard,
Marc.

**Comment by rahmanih** [comment]
great!
closing the issue.
